### ISSUE TITLE
FC3 not working?

### ISSUE THREAD

**Issue by andyp17** [krakul/modbus-rtu-slave#2]
Hello,
Thanks for the node - this is exactly what I need. But I am faced with a problem with FC3. Reading bits from coils works fine (FC1 and FC2) -> I inject the the data with your provided node (Modbus-RTU-Writer to address 1 or 10001). But when I set an in16 Value to address 30001 i always get 0 on reading FC3.
Do you have any ideas? Thanks!!!

KR
Andreas

**Comment by Gh0st90** [comment]
Hey Andreas,
30001 is a input register. For this you have to use FC04.
Greetings

**Comment by andyp17** [comment]
Of course - my fault... 🤦🏼‍♂️🤦🏼‍♂️
Now it works! Many thanks!!

KR
Andreas
