### ISSUE TITLE
FC16 and representing values as each message

### ISSUE THREAD

**Issue by LiquidOcelot29** [krakul/modbus-rtu-slave#4]
Hello, it's great to have such a great node, it's very helpful, but it's a little problem(?) or inconvenience.

Things looks like when I using a FC16 from my PLC the message looks that:

```
ModbusRTURequest {
  _address: 1,
  _body: WriteMultipleRegistersRequestBody {
    _fc: 16,
    _address: 0,
    _values: <Buffer 00 00 00 64 00 00 01 2c 00 00 00 00 02 58 00 00 00 00 00 00>,
    _byteCount: 26,
    _numberOfBytes: 20,
    _quantity: 10,
    _valuesAsBuffer: <Buffer 00 00 00 64 00 00 01 2c 00 00 00 00 02 58 00 00 00 00 00 00>,
    _valuesAsArray: [
      0, 100, 0, 300, 0,
      0, 600, 0,   0, 0
    ]
  },
  _corrupted: false
}
```

The values that I'm intersted are in array "_valuesAsArray:". Is it possible to modify the node that will output values directly as each payload or something like that? Currently is possible to manage with those values by build function that will extract them or use other nodes to isolate rest of the information from message.

After all, I emphasise that this is a very good, useful and helpful node
Greetings

**Comment by kommando828** [comment]
Use a switch node after the Register Poll to filter out everything but _valuesAsArray and then the next node can operate on these values.

**Comment by JaagupAverin** [comment]
Hey. Sorry this is not actively maintained by us for QoL features, but kommando's suggestion should work.
